//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Laser_sys
//  @ File Name : SimpleThread.cpp
//  @ Date : 2017/7/4
//  @ Author : 
//
//


#include <cstdio>
#include "SimpleThread.h"




void SimpleThread::Start(char* ThreadName) {
	name = ThreadName;
	THreadHandle = CreateThread(NULL, 0, ThreadEntryWarp, this, 0, NULL);
}

//Won't stop immediately
void SimpleThread::Stop() {
	CloseHandle(THreadHandle);
}

void SimpleThread::SetRun(void(*FuncPtr)(void* Owner) , void* Owner) {
	RunWarp = FuncPtr;
	RunWarpOwner = Owner;
}

DWORD WINAPI SimpleThread::ThreadEntryWarp(LPVOID lpParameter) {
	SimpleThread* thread = (SimpleThread*)(lpParameter);
	thread->ThreadRunner();
	return 0;
}

void SimpleThread::ThreadRunner()
{

	if (RunWarp != NULL && RunWarpOwner != NULL) {
		RunWarp(RunWarpOwner);
	}
	//Run End
}
