//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Laser_sys
//  @ File Name : LayserServer.h
//  @ Date : 2017/7/4
//  @ Author : 
//
//


#if !defined(_LAYSERSERVER_H)
#define _LAYSERSERVER_H

#include <vector>
#include <map>

#include "ReadSensorInterface.h"
#include "SocketRead.h"
#include "SerialRead.h"
#include "Tracker.h"
#include "SimpleThread.h"
#include "common\mavlink.h"
using namespace std;

class LayserServer {
protected:
	enum READ_MODE{SERIAL_MODE, SOCKET_MODE};
public:
	LayserServer();
	virtual ~LayserServer();
	void Start();
	void Stop();
	bool setGenIdMapRealID(int GenID, int RealID);
	vector<Tracker*>* GetTrackers();
private:
	// Server Threads
	SimpleThread* ReadThread;
	SimpleThread* SendThread;
	

	static void ReadDataRunWarp(void* Owner);
	static void SendDataRunWarp(void* Owner);

	void ReadDataRun();
	void SendDataRun();

	bool ReadContinueFlag;
	bool SendContinueFlag;

	//PNP Calculat
	void EPnpCalculate(uint8_t channel, mavlink_sensor_time_t pck);
	mavlink_sensor_time_t sensorPck;

	//Read
	READ_MODE selectedMode = SOCKET_MODE;
	ReadSensorInterface* readInterface;
	int portSend = 7777;						//UDP Send
	static const int MAX_BUFFER = 2048;
	char decodeBuffer[MAX_BUFFER];
	CRITICAL_SECTION g_cs;
	int readedBufferLen = 0;

	//Decode
	void DecodeMavlink(uint8_t channel, char* data, int len);
	mavlink_message_t DecodeMsg[MAX_TRACKER_NUM + 5];
	mavlink_status_t status;
	mavlink_attitude_quaternion_t quatPck;
	

	//Tacker 
	vector<Tracker*> *Trackers;
	vector<Tracker*> *TrackersCpy;
	CRITICAL_SECTION TrackersCpyLock;
	Tracker ReadTracker[MAX_TRACKER_NUM + 5];
	map<char*, Tracker*> TrackerMap;
	uint8_t MavSendBuffer[MAX_TRACKER_NUM + 5][1024];
	mavlink_message_t EncodeMsg[MAX_TRACKER_NUM + 5];
	mavlink_t_tracker_t ToSendTracker;
	void MulticastTrackerData(SOCKET &s, sockaddr_in &remote);

	//Tracer ID Managememt 
	bool IsGenIDExist[MAX_TRACKER_NUM + 5];
	bool IsRealIDExist[MAX_TRACKER_NUM + 5];
	int NextGenID[MAX_TRACKER_NUM + 5];
	void InitID();
	int GenID();
	int DelID(int id);
	map<char*, int>addrMapGenID;
	double GenIDMapTimeTick[MAX_TRACKER_NUM + 5];
	int GenIDMapRealID[MAX_TRACKER_NUM + 5];
	int RealIDMapGenID[MAX_TRACKER_NUM + 5];
	static const double IP_TIME_OUT;//second
	

};

#endif  //_LAYSERSERVER_H
