//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Laser_sys
//  @ File Name : SerialRead.cpp
//  @ Date : 2018/1/3
//  @ Author : akfheaven
//
//


#include "SerialRead.h"

void SerialRead::Init(char* port, int bautRate) {

}

bool SerialRead::RecieveData(char* data, int& len, char* channel) {
	return false;
}

void SerialRead::close()
{

}

