//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Laser_sys
//  @ File Name : SerialRead.cpp
//  @ Date : 2018/1/3
//  @ Author : akfheaven
//
//

#include <iostream>
#include "SerialRead.h"

using namespace std;
bool SerialRead::Init(char* port, uint32_t baudRate) {
	mPortName = port;
	try
	{
		//my_serial = new serial::Serial(port, baudRate, serial::Timeout::simpleTimeout(0));
		my_serial = new serial::Serial(port, baudRate);// block IO
	}
	catch (const std::exception& aa)
	{
		printf("serial error : %s\n", aa.what());
		return false;
	}
	return true;
}

bool SerialRead::RecieveData(char* data, int& len, char* channel) {
	result = my_serial->read(READ_LEN);
	len = result.length();
	if (len <= 0)return false;
	/*for (int i = 0; i < len; i++) {
		cout << (int)result[i] << " ";
	}cout << endl;*/
	memcpy(data, result.c_str(), len);
	//data = const_cast<char*>(result.c_str());
	channel = mPortName;
	return true;
}

void SerialRead::close()
{
	my_serial->close();
	delete my_serial;
}

