//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Laser_sys
//  @ File Name : SocketRead.h
//  @ Date : 2018/1/3
//  @ Author : akfheaven
//
//


#if !defined(_SOCKETREAD_H)
#define _SOCKETREAD_H

#include "ReadSensorInterface.h"

class SocketRead : public ReadSensorInterface {
public:
	void Init(int port);
	bool RecieveData(char* data, int& len, int& channel);
};

#endif  //_SOCKETREAD_H
