//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Laser_sys
//  @ File Name : SocketRead.cpp
//  @ Date : 2018/1/3
//  @ Author : akfheaven
//
//


#include "SocketRead.h"

void SocketRead::Init(int port) {

}

bool SocketRead::RecieveData(char* data, int& len, int& channel) {

}

