//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Laser_sys
//  @ File Name : TestRead.cpp
//  @ Date : 2018/1/3
//  @ Author : akfheaven
//
//


#include "TestRead.h"

void TestRead::Init() {

}

bool TestRead::RecieveData(char* data, int& len, int& channel) {

}

