//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Laser_sys
//  @ File Name : TestRead.h
//  @ Date : 2018/1/3
//  @ Author : akfheaven
//
//


#if !defined(_TESTREAD_H)
#define _TESTREAD_H

#include "ReadSensorInterface.h"

class TestRead : public ReadSensorInterface {
public:
	void Init();
	bool RecieveData(char* data, int& len, char* channel);
};

#endif  //_TESTREAD_H
