//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Laser_sys
//  @ File Name : Tracker.h
//  @ Date : 2017/7/4
//  @ Author : 
//
//


#if !defined(_TRACKER_H)
#define _TRACKER_H

#ifdef  DLL_API
#define DLL_API __declspec(dllexport)
#else
#define DLL_API __declspec(dllimport)
#endif

#define MAX_TRACKER_NUM 125
#define TRACERS_SHARE_MEM_NAME "trackers_share_memery"

// 每个片子对应一个Tracker
class DLL_API Tracker {
public:
	char Name[5];
	float Qx;
	float Qy;
	float Qz;
	float Qw;
	float Px;
	float Py;
	float Pz;
	double timeStemp;
	int ReadId;
	Tracker();

	void Test();
};

#endif  //_TRACKER_H
