//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Laser_sys
//  @ File Name : Tracker.cpp
//  @ Date : 2017/7/4
//  @ Author : 
//
//


#include "Tracker.h"

Tracker::Tracker() {
	Qw = 1;
	Qx = 0;
	Qy = 0;
	Qz = 0;
	Px = 0;
	Py = 0;
	Pz = 0;
	timeStemp = 0;
	ReadId = -1;
	GenId = 0;
}

void Tracker::Test()
{
}

